// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: greet.proto

// package — уникальное имя пакета в мире protobuf

package greetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreetService_SayHello_FullMethodName           = "/greet.GreetService/SayHello"
	GreetService_GetDiscount_FullMethodName        = "/greet.GreetService/GetDiscount"
	GreetService_GetDiscounts_FullMethodName       = "/greet.GreetService/GetDiscounts"
	GreetService_AddDiscount_FullMethodName        = "/greet.GreetService/AddDiscount"
	GreetService_DeactivateDiscount_FullMethodName = "/greet.GreetService/DeactivateDiscount"
)

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GreetService — gRPC сервис promotion-а.
// Basket вызывает эти методы чтобы получить скидки.
type GreetServiceClient interface {
	// SayHello — тестовый метод: проверяем что gRPC работает
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// GetDiscount — получить активную скидку для одного товара
	GetDiscount(ctx context.Context, in *GetDiscountRequest, opts ...grpc.CallOption) (*GetDiscountResponse, error)
	// GetDiscounts — получить скидки для списка товаров сразу (batch)
	GetDiscounts(ctx context.Context, in *GetDiscountsRequest, opts ...grpc.CallOption) (*GetDiscountsResponse, error)
	// AddDiscount — создать новую скидку для товара
	AddDiscount(ctx context.Context, in *AddDiscountRequest, opts ...grpc.CallOption) (*AddDiscountResponse, error)
	// DeactivateDiscount — деактивировать скидку (active=false, запись сохраняется)
	DeactivateDiscount(ctx context.Context, in *DeactivateDiscountRequest, opts ...grpc.CallOption) (*DeactivateDiscountResponse, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GreetService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GetDiscount(ctx context.Context, in *GetDiscountRequest, opts ...grpc.CallOption) (*GetDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscountResponse)
	err := c.cc.Invoke(ctx, GreetService_GetDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GetDiscounts(ctx context.Context, in *GetDiscountsRequest, opts ...grpc.CallOption) (*GetDiscountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscountsResponse)
	err := c.cc.Invoke(ctx, GreetService_GetDiscounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) AddDiscount(ctx context.Context, in *AddDiscountRequest, opts ...grpc.CallOption) (*AddDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDiscountResponse)
	err := c.cc.Invoke(ctx, GreetService_AddDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) DeactivateDiscount(ctx context.Context, in *DeactivateDiscountRequest, opts ...grpc.CallOption) (*DeactivateDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateDiscountResponse)
	err := c.cc.Invoke(ctx, GreetService_DeactivateDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetServiceServer is the server API for GreetService service.
// All implementations must embed UnimplementedGreetServiceServer
// for forward compatibility.
//
// GreetService — gRPC сервис promotion-а.
// Basket вызывает эти методы чтобы получить скидки.
type GreetServiceServer interface {
	// SayHello — тестовый метод: проверяем что gRPC работает
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	// GetDiscount — получить активную скидку для одного товара
	GetDiscount(context.Context, *GetDiscountRequest) (*GetDiscountResponse, error)
	// GetDiscounts — получить скидки для списка товаров сразу (batch)
	GetDiscounts(context.Context, *GetDiscountsRequest) (*GetDiscountsResponse, error)
	// AddDiscount — создать новую скидку для товара
	AddDiscount(context.Context, *AddDiscountRequest) (*AddDiscountResponse, error)
	// DeactivateDiscount — деактивировать скидку (active=false, запись сохраняется)
	DeactivateDiscount(context.Context, *DeactivateDiscountRequest) (*DeactivateDiscountResponse, error)
	mustEmbedUnimplementedGreetServiceServer()
}

// UnimplementedGreetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreetServiceServer struct{}

func (UnimplementedGreetServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServiceServer) GetDiscount(context.Context, *GetDiscountRequest) (*GetDiscountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscount not implemented")
}
func (UnimplementedGreetServiceServer) GetDiscounts(context.Context, *GetDiscountsRequest) (*GetDiscountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscounts not implemented")
}
func (UnimplementedGreetServiceServer) AddDiscount(context.Context, *AddDiscountRequest) (*AddDiscountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDiscount not implemented")
}
func (UnimplementedGreetServiceServer) DeactivateDiscount(context.Context, *DeactivateDiscountRequest) (*DeactivateDiscountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateDiscount not implemented")
}
func (UnimplementedGreetServiceServer) mustEmbedUnimplementedGreetServiceServer() {}
func (UnimplementedGreetServiceServer) testEmbeddedByValue()                      {}

// UnsafeGreetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiceServer will
// result in compilation errors.
type UnsafeGreetServiceServer interface {
	mustEmbedUnimplementedGreetServiceServer()
}

func RegisterGreetServiceServer(s grpc.ServiceRegistrar, srv GreetServiceServer) {
	// If the following call panics, it indicates UnimplementedGreetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreetService_ServiceDesc, srv)
}

func _GreetService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetService_GetDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GetDiscount(ctx, req.(*GetDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GetDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GetDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetService_GetDiscounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GetDiscounts(ctx, req.(*GetDiscountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_AddDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).AddDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetService_AddDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).AddDiscount(ctx, req.(*AddDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_DeactivateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).DeactivateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetService_DeactivateDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).DeactivateDiscount(ctx, req.(*DeactivateDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetService_ServiceDesc is the grpc.ServiceDesc for GreetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetService_SayHello_Handler,
		},
		{
			MethodName: "GetDiscount",
			Handler:    _GreetService_GetDiscount_Handler,
		},
		{
			MethodName: "GetDiscounts",
			Handler:    _GreetService_GetDiscounts_Handler,
		},
		{
			MethodName: "AddDiscount",
			Handler:    _GreetService_AddDiscount_Handler,
		},
		{
			MethodName: "DeactivateDiscount",
			Handler:    _GreetService_DeactivateDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet.proto",
}
