// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: greet.proto

// package — уникальное имя пакета в мире protobuf

package greetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Имя для приветствия (например, "basket-service")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Ответ: "Hello, basket-service!"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // UUID товара из каталога
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountRequest) Reset() {
	*x = GetDiscountRequest{}
	mi := &file_greet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountRequest) ProtoMessage() {}

func (x *GetDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountRequest.ProtoReflect.Descriptor instead.
func (*GetDiscountRequest) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiscountRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetDiscountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // UUID товара
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`           // Процент скидки (0 если нет скидки)
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`              // Есть ли активная скидка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountResponse) Reset() {
	*x = GetDiscountResponse{}
	mi := &file_greet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountResponse) ProtoMessage() {}

func (x *GetDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountResponse.ProtoReflect.Descriptor instead.
func (*GetDiscountResponse) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiscountResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetDiscountResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *GetDiscountResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetDiscountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"` // Список UUID товаров
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountsRequest) Reset() {
	*x = GetDiscountsRequest{}
	mi := &file_greet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountsRequest) ProtoMessage() {}

func (x *GetDiscountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountsRequest.ProtoReflect.Descriptor instead.
func (*GetDiscountsRequest) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{4}
}

func (x *GetDiscountsRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type GetDiscountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discounts     []*GetDiscountResponse `protobuf:"bytes,1,rep,name=discounts,proto3" json:"discounts,omitempty"` // Скидки для каждого товара
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscountsResponse) Reset() {
	*x = GetDiscountsResponse{}
	mi := &file_greet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountsResponse) ProtoMessage() {}

func (x *GetDiscountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountsResponse.ProtoReflect.Descriptor instead.
func (*GetDiscountsResponse) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{5}
}

func (x *GetDiscountsResponse) GetDiscounts() []*GetDiscountResponse {
	if x != nil {
		return x.Discounts
	}
	return nil
}

type AddDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // UUID товара из каталога
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`                 // Процент скидки (0-100)
	StartsAt      string                 `protobuf:"bytes,3,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"` // Начало действия RFC3339 (пустая строка = сразу)
	EndsAt        string                 `protobuf:"bytes,4,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`       // Конец действия RFC3339 (пустая строка = бессрочно)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiscountRequest) Reset() {
	*x = AddDiscountRequest{}
	mi := &file_greet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiscountRequest) ProtoMessage() {}

func (x *AddDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiscountRequest.ProtoReflect.Descriptor instead.
func (*AddDiscountRequest) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{6}
}

func (x *AddDiscountRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddDiscountRequest) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *AddDiscountRequest) GetStartsAt() string {
	if x != nil {
		return x.StartsAt
	}
	return ""
}

func (x *AddDiscountRequest) GetEndsAt() string {
	if x != nil {
		return x.EndsAt
	}
	return ""
}

type AddDiscountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscountId    string                 `protobuf:"bytes,1,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"` // UUID созданной скидки
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`                                  // true если скидка успешно создана
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiscountResponse) Reset() {
	*x = AddDiscountResponse{}
	mi := &file_greet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiscountResponse) ProtoMessage() {}

func (x *AddDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiscountResponse.ProtoReflect.Descriptor instead.
func (*AddDiscountResponse) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{7}
}

func (x *AddDiscountResponse) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

func (x *AddDiscountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeactivateDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscountId    string                 `protobuf:"bytes,1,opt,name=discount_id,json=discountId,proto3" json:"discount_id,omitempty"` // UUID скидки которую нужно деактивировать
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateDiscountRequest) Reset() {
	*x = DeactivateDiscountRequest{}
	mi := &file_greet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateDiscountRequest) ProtoMessage() {}

func (x *DeactivateDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateDiscountRequest.ProtoReflect.Descriptor instead.
func (*DeactivateDiscountRequest) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateDiscountRequest) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

type DeactivateDiscountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"` // true если скидка успешно деактивирована
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateDiscountResponse) Reset() {
	*x = DeactivateDiscountResponse{}
	mi := &file_greet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateDiscountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateDiscountResponse) ProtoMessage() {}

func (x *DeactivateDiscountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateDiscountResponse.ProtoReflect.Descriptor instead.
func (*DeactivateDiscountResponse) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateDiscountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_greet_proto protoreflect.FileDescriptor

const file_greet_proto_rawDesc = "" +
	"\n" +
	"\vgreet.proto\x12\x05greet\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x12GetDiscountRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"`\n" +
	"\x13GetDiscountResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"0\n" +
	"\x13GetDiscountsRequest\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds\"P\n" +
	"\x14GetDiscountsResponse\x128\n" +
	"\tdiscounts\x18\x01 \x03(\v2\x1a.greet.GetDiscountResponseR\tdiscounts\"}\n" +
	"\x12AddDiscountRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x1b\n" +
	"\tstarts_at\x18\x03 \x01(\tR\bstartsAt\x12\x17\n" +
	"\aends_at\x18\x04 \x01(\tR\x06endsAt\"F\n" +
	"\x13AddDiscountResponse\x12\x1f\n" +
	"\vdiscount_id\x18\x01 \x01(\tR\n" +
	"discountId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"<\n" +
	"\x19DeactivateDiscountRequest\x12\x1f\n" +
	"\vdiscount_id\x18\x01 \x01(\tR\n" +
	"discountId\",\n" +
	"\x1aDeactivateDiscountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xf5\x02\n" +
	"\fGreetService\x125\n" +
	"\bSayHello\x12\x13.greet.HelloRequest\x1a\x14.greet.HelloResponse\x12D\n" +
	"\vGetDiscount\x12\x19.greet.GetDiscountRequest\x1a\x1a.greet.GetDiscountResponse\x12G\n" +
	"\fGetDiscounts\x12\x1a.greet.GetDiscountsRequest\x1a\x1b.greet.GetDiscountsResponse\x12D\n" +
	"\vAddDiscount\x12\x19.greet.AddDiscountRequest\x1a\x1a.greet.AddDiscountResponse\x12Y\n" +
	"\x12DeactivateDiscount\x12 .greet.DeactivateDiscountRequest\x1a!.greet.DeactivateDiscountResponseB5Z3marketplace/internal/promotion/grpc/greetpb;greetpbb\x06proto3"

var (
	file_greet_proto_rawDescOnce sync.Once
	file_greet_proto_rawDescData []byte
)

func file_greet_proto_rawDescGZIP() []byte {
	file_greet_proto_rawDescOnce.Do(func() {
		file_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_proto_rawDesc), len(file_greet_proto_rawDesc)))
	})
	return file_greet_proto_rawDescData
}

var file_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_greet_proto_goTypes = []any{
	(*HelloRequest)(nil),               // 0: greet.HelloRequest
	(*HelloResponse)(nil),              // 1: greet.HelloResponse
	(*GetDiscountRequest)(nil),         // 2: greet.GetDiscountRequest
	(*GetDiscountResponse)(nil),        // 3: greet.GetDiscountResponse
	(*GetDiscountsRequest)(nil),        // 4: greet.GetDiscountsRequest
	(*GetDiscountsResponse)(nil),       // 5: greet.GetDiscountsResponse
	(*AddDiscountRequest)(nil),         // 6: greet.AddDiscountRequest
	(*AddDiscountResponse)(nil),        // 7: greet.AddDiscountResponse
	(*DeactivateDiscountRequest)(nil),  // 8: greet.DeactivateDiscountRequest
	(*DeactivateDiscountResponse)(nil), // 9: greet.DeactivateDiscountResponse
}
var file_greet_proto_depIdxs = []int32{
	3, // 0: greet.GetDiscountsResponse.discounts:type_name -> greet.GetDiscountResponse
	0, // 1: greet.GreetService.SayHello:input_type -> greet.HelloRequest
	2, // 2: greet.GreetService.GetDiscount:input_type -> greet.GetDiscountRequest
	4, // 3: greet.GreetService.GetDiscounts:input_type -> greet.GetDiscountsRequest
	6, // 4: greet.GreetService.AddDiscount:input_type -> greet.AddDiscountRequest
	8, // 5: greet.GreetService.DeactivateDiscount:input_type -> greet.DeactivateDiscountRequest
	1, // 6: greet.GreetService.SayHello:output_type -> greet.HelloResponse
	3, // 7: greet.GreetService.GetDiscount:output_type -> greet.GetDiscountResponse
	5, // 8: greet.GreetService.GetDiscounts:output_type -> greet.GetDiscountsResponse
	7, // 9: greet.GreetService.AddDiscount:output_type -> greet.AddDiscountResponse
	9, // 10: greet.GreetService.DeactivateDiscount:output_type -> greet.DeactivateDiscountResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_greet_proto_init() }
func file_greet_proto_init() {
	if File_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_proto_rawDesc), len(file_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_proto_goTypes,
		DependencyIndexes: file_greet_proto_depIdxs,
		MessageInfos:      file_greet_proto_msgTypes,
	}.Build()
	File_greet_proto = out.File
	file_greet_proto_goTypes = nil
	file_greet_proto_depIdxs = nil
}
